name: update
run-name: '更新启动器公告'
on:
  push:
  workflow_dispatch:
    inputs:
      content:
        description: '公告的内容'
        type: string
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      # 执行.github/scripts/update.cjs脚本
      - name: run update script
        run: |
          echo ${{ github.event.inputs.content }}
          echo --------------------
          python .github/scripts/update.py ${{ github.event.inputs.content }}
      # 提交更新后的文件
      - name: commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add announcement.json
          commit_message=$(echo "${{ github.event.inputs.content }}" | cut -c1-10)
          git commit -m "$commit_message"
          git push
        continue-on-error: true

      - name: Upload updater.json to R2
        uses: gemwalletcom/r2-upload@v1.0.0
        with:
          endpoint: ${{ secrets.R2_ENDPOINT }}
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          bucket: hyzl
          file: './announcement.json'
          destination: 'announcement/announcement.json'
