name: update
run-name: '更新启动器日志'
on:
  push:
  workflow_dispatch:

jobs:
  refresh-jsdelivr:
    runs-on: ubuntu-latest
    steps:
      - name: Hub Mirror Action.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/bling-yshs
          dst: gitee/bling_yshs
          dst_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
